Repository EMMC-ASBL/tripper, pull requests merged in 2022-10, with the labels that each got.

#5 Clean up repository & fix workflows
  .github/workflows/cd_release.yml
  .github/workflows/ci_cd_updated_main.yml
  .github/workflows/ci_check_dependencies.yml
  .github/workflows/ci_tests.yml
  .github/workflows/ci_update_dependencies.yml
  .pre-commit-config.yaml
  docs/api_reference/.pages
  docs/api_reference/backends/.pages
  docs/api_reference/backends/ontopy.md
  docs/api_reference/backends/rdflib.md
  docs/api_reference/interface.md
  docs/api_reference/triplestore.md
  docs/index.md
  docs/overview.md
  mkdocs.yml
  pyproject.toml
  tests/conftest.py
  tests/test_literals.py
  tests/test_namespace.py
  tests/test_triplestore.py
  tripper/README.md
  tripper/__init__.py
  tripper/backends/__init__.py
  tripper/backends/allegrograph.py
  tripper/backends/ontopy.py
  tripper/backends/rdflib.py
  tripper/interface.py
  tripper/requirements.txt
  tripper/requirements_dev.txt
  tripper/triplestore.py
Labels: Priority: High, BLOCKING

#17 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI/CD, skip_changelog

#21 Corrected copyright
  LICENSE
  README.md
  docs/index.md
  mkdocs.yml
Labels: Priority: High
